version: "3.7"

services:
  postgres:
    container_name: postgres_database
    image: postgres:14.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sandboxdb}
      POSTGRES_USER: ${POSTGRES_USER:-pgadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./bin/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dbnetwork
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    user: root:root
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./bin/pgadmin/postgres:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - dbnetwork
    restart: unless-stopped

networks:
  dbnetwork:
    driver: bridge


